spring.application.name=payment-service
server.port=${SERVER_PORT:8768}

# Config Server ba?lant?s?
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

# Profil
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Management / Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

# Di?er
spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name}] [%thread] %logger{36} - %msg%n

# Iyzico sandbox
iyzico.base-url=${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
iyzico.api-key=${IYZICO_API_KEY:sandbox-9EhnVupXOh9VBM5cmxO2lsmPtvScZNWB}
iyzico.secret-key=${IYZICO_SECRET_KEY:sandbox-oXvcLVCecnptCoJFW144CUx1cndra1cg}
iyzico.test-card.holder-name=${IYZICO_TEST_CARD_HOLDER_NAME:John Doe}
iyzico.test-card.number=${IYZICO_TEST_CARD_NUMBER:5528790000000008}
iyzico.test-card.expire-month=${IYZICO_TEST_CARD_EXPIRE_MONTH:12}
iyzico.test-card.expire-year=${IYZICO_TEST_CARD_EXPIRE_YEAR:2030}
iyzico.test-card.cvc=${IYZICO_TEST_CARD_CVC:123}
