server.port=8769

spring.application.name=stock-service

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/n11bootcamp
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# LOGGING
logging.level.org.springframework=INFO

# RabbitMQ (SAGA)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest